services:
  db:
    image: postgres:16
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data/pgdata
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  api:
    image: flexappeal-api
    restart: always
    depends_on:
      - db 
    env_file: .env
    environment:
    - DB_URI=postgresql://postgres:password@db/postgres
    - BACKEND_CORS_ORIGINS=["http://localhost", "http://frontend"]
    expose:
      - 80

    build:
      context: ./api

  frontend:
    image: flexappeal-frontend
    restart: always
    ports:
      - "80:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/api
        # - NODE_ENV=production

volumes:
  db-data: